[build]
  publish = "."

[[headers]]
  for = "/c/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/c/_shared/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/c/*/*.vcf"
  [headers.values]
    Content-Type = "text/vcard; charset=utf-8"
    Content-Disposition = "attachment"
