/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FanReactionsRouteImport } from './routes/fan-reactions'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LiveRouteImport } from './routes/live'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as RobloxPortalRouteImport } from './routes/roblox.portal'
import { Route as TechnologySlugRouteImport } from './routes/technology.$slug'
import { Route as RobloxPortalIndexRouteImport } from './routes/roblox.portal.index'
import { Route as RobloxPortalApplyRouteImport } from './routes/roblox.portal.apply'
import { Route as RobloxPortalGuidelinesRouteImport } from './routes/roblox.portal.guidelines'
import { Route as RobloxPortalPerformanceRouteImport } from './routes/roblox.portal.performance'
import { Route as RobloxPortalProductsRouteImport } from './routes/roblox.portal.products'
import { Route as RobloxPortalResourcesRouteImport } from './routes/roblox.portal.resources'
import { Route as RobloxPortalReviewRouteImport } from './routes/roblox.portal.review'
import { Route as RobloxPortalStatusRouteImport } from './routes/roblox.portal.status'
import { Route as RobloxPortalSupportRouteImport } from './routes/roblox.portal.support'
import { Route as RobloxPortalSubmissionsIndexRouteImport } from './routes/roblox.portal.submissions.index'
import { Route as RobloxPortalSubmissionsIdRouteImport } from './routes/roblox.portal.submissions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FanReactionsRoute = FanReactionsRouteImport.update({
  id: '/fan-reactions',
  path: '/fan-reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxPortalRoute = RobloxPortalRouteImport.update({
  id: '/roblox/portal',
  path: '/roblox/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologySlugRoute = TechnologySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TechnologyRoute,
} as any)
const RobloxPortalIndexRoute = RobloxPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalApplyRoute = RobloxPortalApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalGuidelinesRoute = RobloxPortalGuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalPerformanceRoute = RobloxPortalPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalProductsRoute = RobloxPortalProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalResourcesRoute = RobloxPortalResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalReviewRoute = RobloxPortalReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalStatusRoute = RobloxPortalStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalSupportRoute = RobloxPortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => RobloxPortalRoute,
} as any)
const RobloxPortalSubmissionsIndexRoute =
  RobloxPortalSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => RobloxPortalRoute,
  } as any)
const RobloxPortalSubmissionsIdRoute =
  RobloxPortalSubmissionsIdRouteImport.update({
    id: '/submissions/$id',
    path: '/submissions/$id',
    getParentRoute: () => RobloxPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/fan-reactions': typeof FanReactionsRoute
  '/insights': typeof InsightsRoute
  '/live': typeof LiveRoute
  '/technology': typeof TechnologyRouteWithChildren
  '/roblox/portal': typeof RobloxPortalRouteWithChildren
  '/technology/$slug': typeof TechnologySlugRoute
  '/roblox/portal/apply': typeof RobloxPortalApplyRoute
  '/roblox/portal/guidelines': typeof RobloxPortalGuidelinesRoute
  '/roblox/portal/performance': typeof RobloxPortalPerformanceRoute
  '/roblox/portal/products': typeof RobloxPortalProductsRoute
  '/roblox/portal/resources': typeof RobloxPortalResourcesRoute
  '/roblox/portal/review': typeof RobloxPortalReviewRoute
  '/roblox/portal/status': typeof RobloxPortalStatusRoute
  '/roblox/portal/support': typeof RobloxPortalSupportRoute
  '/roblox/portal/': typeof RobloxPortalIndexRoute
  '/roblox/portal/submissions/$id': typeof RobloxPortalSubmissionsIdRoute
  '/roblox/portal/submissions/': typeof RobloxPortalSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/fan-reactions': typeof FanReactionsRoute
  '/insights': typeof InsightsRoute
  '/live': typeof LiveRoute
  '/technology': typeof TechnologyRouteWithChildren
  '/technology/$slug': typeof TechnologySlugRoute
  '/roblox/portal/apply': typeof RobloxPortalApplyRoute
  '/roblox/portal/guidelines': typeof RobloxPortalGuidelinesRoute
  '/roblox/portal/performance': typeof RobloxPortalPerformanceRoute
  '/roblox/portal/products': typeof RobloxPortalProductsRoute
  '/roblox/portal/resources': typeof RobloxPortalResourcesRoute
  '/roblox/portal/review': typeof RobloxPortalReviewRoute
  '/roblox/portal/status': typeof RobloxPortalStatusRoute
  '/roblox/portal/support': typeof RobloxPortalSupportRoute
  '/roblox/portal': typeof RobloxPortalIndexRoute
  '/roblox/portal/submissions/$id': typeof RobloxPortalSubmissionsIdRoute
  '/roblox/portal/submissions': typeof RobloxPortalSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/fan-reactions': typeof FanReactionsRoute
  '/insights': typeof InsightsRoute
  '/live': typeof LiveRoute
  '/technology': typeof TechnologyRouteWithChildren
  '/roblox/portal': typeof RobloxPortalRouteWithChildren
  '/technology/$slug': typeof TechnologySlugRoute
  '/roblox/portal/apply': typeof RobloxPortalApplyRoute
  '/roblox/portal/guidelines': typeof RobloxPortalGuidelinesRoute
  '/roblox/portal/performance': typeof RobloxPortalPerformanceRoute
  '/roblox/portal/products': typeof RobloxPortalProductsRoute
  '/roblox/portal/resources': typeof RobloxPortalResourcesRoute
  '/roblox/portal/review': typeof RobloxPortalReviewRoute
  '/roblox/portal/status': typeof RobloxPortalStatusRoute
  '/roblox/portal/support': typeof RobloxPortalSupportRoute
  '/roblox/portal/': typeof RobloxPortalIndexRoute
  '/roblox/portal/submissions/$id': typeof RobloxPortalSubmissionsIdRoute
  '/roblox/portal/submissions/': typeof RobloxPortalSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/case-studies'
    | '/contact'
    | '/fan-reactions'
    | '/insights'
    | '/live'
    | '/technology'
    | '/roblox/portal'
    | '/technology/$slug'
    | '/roblox/portal/apply'
    | '/roblox/portal/guidelines'
    | '/roblox/portal/performance'
    | '/roblox/portal/products'
    | '/roblox/portal/resources'
    | '/roblox/portal/review'
    | '/roblox/portal/status'
    | '/roblox/portal/support'
    | '/roblox/portal/'
    | '/roblox/portal/submissions/$id'
    | '/roblox/portal/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/case-studies'
    | '/contact'
    | '/fan-reactions'
    | '/insights'
    | '/live'
    | '/technology'
    | '/technology/$slug'
    | '/roblox/portal/apply'
    | '/roblox/portal/guidelines'
    | '/roblox/portal/performance'
    | '/roblox/portal/products'
    | '/roblox/portal/resources'
    | '/roblox/portal/review'
    | '/roblox/portal/status'
    | '/roblox/portal/support'
    | '/roblox/portal'
    | '/roblox/portal/submissions/$id'
    | '/roblox/portal/submissions'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/case-studies'
    | '/contact'
    | '/fan-reactions'
    | '/insights'
    | '/live'
    | '/technology'
    | '/roblox/portal'
    | '/technology/$slug'
    | '/roblox/portal/apply'
    | '/roblox/portal/guidelines'
    | '/roblox/portal/performance'
    | '/roblox/portal/products'
    | '/roblox/portal/resources'
    | '/roblox/portal/review'
    | '/roblox/portal/status'
    | '/roblox/portal/support'
    | '/roblox/portal/'
    | '/roblox/portal/submissions/$id'
    | '/roblox/portal/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  FanReactionsRoute: typeof FanReactionsRoute
  InsightsRoute: typeof InsightsRoute
  LiveRoute: typeof LiveRoute
  TechnologyRoute: typeof TechnologyRouteWithChildren
  RobloxPortalRoute: typeof RobloxPortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-reactions': {
      id: '/fan-reactions'
      path: '/fan-reactions'
      fullPath: '/fan-reactions'
      preLoaderRoute: typeof FanReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox/portal': {
      id: '/roblox/portal'
      path: '/roblox/portal'
      fullPath: '/roblox/portal'
      preLoaderRoute: typeof RobloxPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/$slug': {
      id: '/technology/$slug'
      path: '/$slug'
      fullPath: '/technology/$slug'
      preLoaderRoute: typeof TechnologySlugRouteImport
      parentRoute: typeof TechnologyRoute
    }
    '/roblox/portal/': {
      id: '/roblox/portal/'
      path: '/'
      fullPath: '/roblox/portal/'
      preLoaderRoute: typeof RobloxPortalIndexRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/apply': {
      id: '/roblox/portal/apply'
      path: '/apply'
      fullPath: '/roblox/portal/apply'
      preLoaderRoute: typeof RobloxPortalApplyRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/guidelines': {
      id: '/roblox/portal/guidelines'
      path: '/guidelines'
      fullPath: '/roblox/portal/guidelines'
      preLoaderRoute: typeof RobloxPortalGuidelinesRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/performance': {
      id: '/roblox/portal/performance'
      path: '/performance'
      fullPath: '/roblox/portal/performance'
      preLoaderRoute: typeof RobloxPortalPerformanceRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/products': {
      id: '/roblox/portal/products'
      path: '/products'
      fullPath: '/roblox/portal/products'
      preLoaderRoute: typeof RobloxPortalProductsRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/resources': {
      id: '/roblox/portal/resources'
      path: '/resources'
      fullPath: '/roblox/portal/resources'
      preLoaderRoute: typeof RobloxPortalResourcesRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/review': {
      id: '/roblox/portal/review'
      path: '/review'
      fullPath: '/roblox/portal/review'
      preLoaderRoute: typeof RobloxPortalReviewRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/status': {
      id: '/roblox/portal/status'
      path: '/status'
      fullPath: '/roblox/portal/status'
      preLoaderRoute: typeof RobloxPortalStatusRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/support': {
      id: '/roblox/portal/support'
      path: '/support'
      fullPath: '/roblox/portal/support'
      preLoaderRoute: typeof RobloxPortalSupportRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/submissions/': {
      id: '/roblox/portal/submissions/'
      path: '/submissions'
      fullPath: '/roblox/portal/submissions/'
      preLoaderRoute: typeof RobloxPortalSubmissionsIndexRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
    '/roblox/portal/submissions/$id': {
      id: '/roblox/portal/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/roblox/portal/submissions/$id'
      preLoaderRoute: typeof RobloxPortalSubmissionsIdRouteImport
      parentRoute: typeof RobloxPortalRoute
    }
  }
}

interface TechnologyRouteChildren {
  TechnologySlugRoute: typeof TechnologySlugRoute
}

const TechnologyRouteChildren: TechnologyRouteChildren = {
  TechnologySlugRoute: TechnologySlugRoute,
}

const TechnologyRouteWithChildren = TechnologyRoute._addFileChildren(
  TechnologyRouteChildren,
)

interface RobloxPortalRouteChildren {
  RobloxPortalApplyRoute: typeof RobloxPortalApplyRoute
  RobloxPortalGuidelinesRoute: typeof RobloxPortalGuidelinesRoute
  RobloxPortalPerformanceRoute: typeof RobloxPortalPerformanceRoute
  RobloxPortalProductsRoute: typeof RobloxPortalProductsRoute
  RobloxPortalResourcesRoute: typeof RobloxPortalResourcesRoute
  RobloxPortalReviewRoute: typeof RobloxPortalReviewRoute
  RobloxPortalStatusRoute: typeof RobloxPortalStatusRoute
  RobloxPortalSupportRoute: typeof RobloxPortalSupportRoute
  RobloxPortalIndexRoute: typeof RobloxPortalIndexRoute
  RobloxPortalSubmissionsIdRoute: typeof RobloxPortalSubmissionsIdRoute
  RobloxPortalSubmissionsIndexRoute: typeof RobloxPortalSubmissionsIndexRoute
}

const RobloxPortalRouteChildren: RobloxPortalRouteChildren = {
  RobloxPortalApplyRoute: RobloxPortalApplyRoute,
  RobloxPortalGuidelinesRoute: RobloxPortalGuidelinesRoute,
  RobloxPortalPerformanceRoute: RobloxPortalPerformanceRoute,
  RobloxPortalProductsRoute: RobloxPortalProductsRoute,
  RobloxPortalResourcesRoute: RobloxPortalResourcesRoute,
  RobloxPortalReviewRoute: RobloxPortalReviewRoute,
  RobloxPortalStatusRoute: RobloxPortalStatusRoute,
  RobloxPortalSupportRoute: RobloxPortalSupportRoute,
  RobloxPortalIndexRoute: RobloxPortalIndexRoute,
  RobloxPortalSubmissionsIdRoute: RobloxPortalSubmissionsIdRoute,
  RobloxPortalSubmissionsIndexRoute: RobloxPortalSubmissionsIndexRoute,
}

const RobloxPortalRouteWithChildren = RobloxPortalRoute._addFileChildren(
  RobloxPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  FanReactionsRoute: FanReactionsRoute,
  InsightsRoute: InsightsRoute,
  LiveRoute: LiveRoute,
  TechnologyRoute: TechnologyRouteWithChildren,
  RobloxPortalRoute: RobloxPortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
