/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FanReactionsRouteImport } from './routes/fan-reactions'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LiveRouteImport } from './routes/live'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TechnologySlugRouteImport } from './routes/technology.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FanReactionsRoute = FanReactionsRouteImport.update({
  id: '/fan-reactions',
  path: '/fan-reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologySlugRoute = TechnologySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TechnologyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/fan-reactions': typeof FanReactionsRoute
  '/insights': typeof InsightsRoute
  '/live': typeof LiveRoute
  '/technology': typeof TechnologyRouteWithChildren
  '/technology/$slug': typeof TechnologySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/fan-reactions': typeof FanReactionsRoute
  '/insights': typeof InsightsRoute
  '/live': typeof LiveRoute
  '/technology': typeof TechnologyRouteWithChildren
  '/technology/$slug': typeof TechnologySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/fan-reactions': typeof FanReactionsRoute
  '/insights': typeof InsightsRoute
  '/live': typeof LiveRoute
  '/technology': typeof TechnologyRouteWithChildren
  '/technology/$slug': typeof TechnologySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/case-studies'
    | '/contact'
    | '/fan-reactions'
    | '/insights'
    | '/live'
    | '/technology'
    | '/technology/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/case-studies'
    | '/contact'
    | '/fan-reactions'
    | '/insights'
    | '/live'
    | '/technology'
    | '/technology/$slug'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/case-studies'
    | '/contact'
    | '/fan-reactions'
    | '/insights'
    | '/live'
    | '/technology'
    | '/technology/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  FanReactionsRoute: typeof FanReactionsRoute
  InsightsRoute: typeof InsightsRoute
  LiveRoute: typeof LiveRoute
  TechnologyRoute: typeof TechnologyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-reactions': {
      id: '/fan-reactions'
      path: '/fan-reactions'
      fullPath: '/fan-reactions'
      preLoaderRoute: typeof FanReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/$slug': {
      id: '/technology/$slug'
      path: '/$slug'
      fullPath: '/technology/$slug'
      preLoaderRoute: typeof TechnologySlugRouteImport
      parentRoute: typeof TechnologyRoute
    }
  }
}

interface TechnologyRouteChildren {
  TechnologySlugRoute: typeof TechnologySlugRoute
}

const TechnologyRouteChildren: TechnologyRouteChildren = {
  TechnologySlugRoute: TechnologySlugRoute,
}

const TechnologyRouteWithChildren = TechnologyRoute._addFileChildren(
  TechnologyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  FanReactionsRoute: FanReactionsRoute,
  InsightsRoute: InsightsRoute,
  LiveRoute: LiveRoute,
  TechnologyRoute: TechnologyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
